### ISSUE TITLE
How do we verify backup codes generated with key?

### ISSUE THREAD

**Issue by lakshaygaur** [simontabor/2fa#6]
What is the method to verify backup codes generated at start with key ? verifying with `tfa.verifyTOTP()` or HOTP returns `false`

**Comment by soubhikchatterjee** [comment]
Why is this issue closed without any acknowlegement?

**Comment by KaKi87** [comment]
The answer is that these backup codes are not generated with the key.
There is no `key` parameter in the `tfa.generateBackupCodes` method.
And, it will never be, since the TOTP protocol actually doesn't have such feature as backup codes.
So, the only way to verify backup codes is to store these yourself.
